name: Auto-merge Ansible PRs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge PRs from service account
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.info("No PR object.");
              return;
            }
            const serviceLogin = "asrivastavagithub"; // change to your service account
            if (pr.user && pr.user.login === serviceLogin) {
              // Optionally run checks here (status, reviewers, etc.)
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: "squash"
              });
              core.info(`Merged PR #${pr.number} from ${serviceLogin}`);
            } else {
              core.info(`PR not from ${serviceLogin} — skipping`);
            }
