name: Auto-merge Ansible PRs
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-merge PRs from service account
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.info("No PR object found.");
              return;
            }

            const serviceLogin = "asrivastavagithub"; // 👈 change to your service account username

            if (pr.user && pr.user.login === serviceLogin) {
              core.info(`Merging PR #${pr.number} from ${serviceLogin}...`);
              
              // Merge the PR
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: "squash"
              });

              core.info(`✅ Successfully merged PR #${pr.number}`);

              // Delete the source branch (if not from a fork)
              const branchRef = pr.head.ref;
              if (!pr.head.repo.fork) {
                try {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `heads/${branchRef}`,
                  });
                  core.info(`🧹 Deleted branch ${branchRef}`);
                } catch (error) {
                  core.warning(`Could not delete branch ${branchRef}: ${error.message}`);
                }
              } else {
                core.info("PR came from a fork; skipping branch deletion.");
              }

            } else {
              core.info(`PR not from ${serviceLogin} — skipping auto merge.`);
            }
